### ISSUE TITLE
Image resize method causes issues with transparent images

### ISSUE THREAD

**Issue by karlbright** [envato/imageresize#3]
As shown in https://github.com/envato-sites/sites-theme-tooling/pull/246, when transparent images are resized, you end up with odd results, often appearing to have black drop shadows, or black spots over the image.

To look in to how best to handle this, i've looked into the various image resize methods provided by the resize library we are using, both with a transparent image(with png), and a non-transparent image(with jpg).

---
### Nearest-neighbor interpolation

![nearest](https://cloud.githubusercontent.com/assets/20490/16259534/b3355462-3895-11e6-8510-3ed7bb57ada3.png)
### Bicubic interpolation (Currently used method)

![bicubic](https://cloud.githubusercontent.com/assets/20490/16259532/b19b4a58-3895-11e6-9a35-cdfbd0216611.png)
### Bilinear interpolation

![bilinear](https://cloud.githubusercontent.com/assets/20490/16259530/b06234a8-3895-11e6-895a-dde641230306.png)
### Lanczos resampling with a=2

![lanczos2](https://cloud.githubusercontent.com/assets/20490/16259527/af1aba98-3895-11e6-92a1-3abbdbede119.png)
### Lanczos resampling with a=3

![lanczos3](https://cloud.githubusercontent.com/assets/20490/16259523/ad6b6d5a-3895-11e6-9413-1f2cfb86cc96.png)
### Mitchell-Netravali interpolation

![mitchel](https://cloud.githubusercontent.com/assets/20490/16259519/a945b636-3895-11e6-8afa-f1a9f0f967db.png)

---
### Nearest-neighbor interpolation

![nearest](https://cloud.githubusercontent.com/assets/20490/16259502/9bf36032-3895-11e6-946c-a22784ec3eed.jpg)
### Bicubic interpolation (Currently used method)

![bicubic](https://cloud.githubusercontent.com/assets/20490/16259504/9e4e22c2-3895-11e6-9c5d-70b3d457ca3f.jpg)
### Bilinear interpolation

![bilinear](https://cloud.githubusercontent.com/assets/20490/16259507/a075352c-3895-11e6-87e0-3e6eab94e25b.jpg)
### Lanczos resampling with a=2

![lanczos2](https://cloud.githubusercontent.com/assets/20490/16259510/a24536e0-3895-11e6-8d7f-cad6c935ca58.jpg)
### Lanczos resampling with a=3

![lanczos3](https://cloud.githubusercontent.com/assets/20490/16259511/a402b57a-3895-11e6-8726-0e4831756db1.jpg)
### Mitchell-Netravali interpolation

![mitchel](https://cloud.githubusercontent.com/assets/20490/16259516/a5dbee52-3895-11e6-9842-ecd28f8b3204.jpg)

---

Based on these two images, it's safe to say that Nearest-neighbor interpolation is the safe best for these. In the main use case for this library we are dealing with logos that are more than likely going to be transparent, or simple flat images.

Keen to get some feedback before putting up a PR for this.

**Comment by karlbright** [comment]
@lancesnider ping

**Comment by lancesnider** [comment]
Looks great! I'm 100% on board making NN the default.
